version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    image: vara_backend
    volumes:
      - ./.env:/app/.env
    ports:
      - '8000:8000'
    # env_file:
    #   - ./.env
    restart: unless-stopped

  web:
    container_name: web
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    # volumes:
    #   - ./static:/static
    ports:
      - "80:80"
    depends_on:
      - api